package com.partner.hlife.pojo;

import java.util.Date;

public class HtCouponNumList {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_coupon_num_list.ID
     *
     * @mbg.generated Sat Apr 29 11:24:18 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_coupon_num_list.COUPON_ID
     *
     * @mbg.generated Sat Apr 29 11:24:18 CST 2017
     */
    private Long couponId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_coupon_num_list.COUPON_NUM
     *
     * @mbg.generated Sat Apr 29 11:24:18 CST 2017
     */
    private String couponNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_coupon_num_list.TYPE
     *
     * @mbg.generated Sat Apr 29 11:24:18 CST 2017
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_coupon_num_list.EXPIRE_TIME
     *
     * @mbg.generated Sat Apr 29 11:24:18 CST 2017
     */
    private Date expireTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_coupon_num_list.CREATE_ON
     *
     * @mbg.generated Sat Apr 29 11:24:18 CST 2017
     */
    private Date createOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_coupon_num_list.UPDATE_ON
     *
     * @mbg.generated Sat Apr 29 11:24:18 CST 2017
     */
    private Date updateOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_coupon_num_list.OPTIMIZED_LOCK
     *
     * @mbg.generated Sat Apr 29 11:24:18 CST 2017
     */
    private Integer optimizedLock;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_coupon_num_list.ID
     *
     * @return the value of ht_coupon_num_list.ID
     *
     * @mbg.generated Sat Apr 29 11:24:18 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_coupon_num_list.ID
     *
     * @param id the value for ht_coupon_num_list.ID
     *
     * @mbg.generated Sat Apr 29 11:24:18 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_coupon_num_list.COUPON_ID
     *
     * @return the value of ht_coupon_num_list.COUPON_ID
     *
     * @mbg.generated Sat Apr 29 11:24:18 CST 2017
     */
    public Long getCouponId() {
        return couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_coupon_num_list.COUPON_ID
     *
     * @param couponId the value for ht_coupon_num_list.COUPON_ID
     *
     * @mbg.generated Sat Apr 29 11:24:18 CST 2017
     */
    public void setCouponId(Long couponId) {
        this.couponId = couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_coupon_num_list.COUPON_NUM
     *
     * @return the value of ht_coupon_num_list.COUPON_NUM
     *
     * @mbg.generated Sat Apr 29 11:24:18 CST 2017
     */
    public String getCouponNum() {
        return couponNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_coupon_num_list.COUPON_NUM
     *
     * @param couponNum the value for ht_coupon_num_list.COUPON_NUM
     *
     * @mbg.generated Sat Apr 29 11:24:18 CST 2017
     */
    public void setCouponNum(String couponNum) {
        this.couponNum = couponNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_coupon_num_list.TYPE
     *
     * @return the value of ht_coupon_num_list.TYPE
     *
     * @mbg.generated Sat Apr 29 11:24:18 CST 2017
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_coupon_num_list.TYPE
     *
     * @param type the value for ht_coupon_num_list.TYPE
     *
     * @mbg.generated Sat Apr 29 11:24:18 CST 2017
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_coupon_num_list.EXPIRE_TIME
     *
     * @return the value of ht_coupon_num_list.EXPIRE_TIME
     *
     * @mbg.generated Sat Apr 29 11:24:18 CST 2017
     */
    public Date getExpireTime() {
        return expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_coupon_num_list.EXPIRE_TIME
     *
     * @param expireTime the value for ht_coupon_num_list.EXPIRE_TIME
     *
     * @mbg.generated Sat Apr 29 11:24:18 CST 2017
     */
    public void setExpireTime(Date expireTime) {
        this.expireTime = expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_coupon_num_list.CREATE_ON
     *
     * @return the value of ht_coupon_num_list.CREATE_ON
     *
     * @mbg.generated Sat Apr 29 11:24:18 CST 2017
     */
    public Date getCreateOn() {
        return createOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_coupon_num_list.CREATE_ON
     *
     * @param createOn the value for ht_coupon_num_list.CREATE_ON
     *
     * @mbg.generated Sat Apr 29 11:24:18 CST 2017
     */
    public void setCreateOn(Date createOn) {
        this.createOn = createOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_coupon_num_list.UPDATE_ON
     *
     * @return the value of ht_coupon_num_list.UPDATE_ON
     *
     * @mbg.generated Sat Apr 29 11:24:18 CST 2017
     */
    public Date getUpdateOn() {
        return updateOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_coupon_num_list.UPDATE_ON
     *
     * @param updateOn the value for ht_coupon_num_list.UPDATE_ON
     *
     * @mbg.generated Sat Apr 29 11:24:18 CST 2017
     */
    public void setUpdateOn(Date updateOn) {
        this.updateOn = updateOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_coupon_num_list.OPTIMIZED_LOCK
     *
     * @return the value of ht_coupon_num_list.OPTIMIZED_LOCK
     *
     * @mbg.generated Sat Apr 29 11:24:18 CST 2017
     */
    public Integer getOptimizedLock() {
        return optimizedLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_coupon_num_list.OPTIMIZED_LOCK
     *
     * @param optimizedLock the value for ht_coupon_num_list.OPTIMIZED_LOCK
     *
     * @mbg.generated Sat Apr 29 11:24:18 CST 2017
     */
    public void setOptimizedLock(Integer optimizedLock) {
        this.optimizedLock = optimizedLock;
    }
}