package com.partner.hlife.pojo;

import java.util.Date;

public class HtCouponInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_coupon_info.ID
     *
     * @mbg.generated Sat Apr 29 11:23:54 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_coupon_info.NAME
     *
     * @mbg.generated Sat Apr 29 11:23:54 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_coupon_info.P_URL
     *
     * @mbg.generated Sat Apr 29 11:23:54 CST 2017
     */
    private String pUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_coupon_info.TYPE
     *
     * @mbg.generated Sat Apr 29 11:23:54 CST 2017
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_coupon_info.C_DESC
     *
     * @mbg.generated Sat Apr 29 11:23:54 CST 2017
     */
    private String cDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_coupon_info.AMT
     *
     * @mbg.generated Sat Apr 29 11:23:54 CST 2017
     */
    private Double amt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_coupon_info.MER_ID
     *
     * @mbg.generated Sat Apr 29 11:23:54 CST 2017
     */
    private Long merId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_coupon_info.AREA
     *
     * @mbg.generated Sat Apr 29 11:23:54 CST 2017
     */
    private Integer area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_coupon_info.USE_RULE
     *
     * @mbg.generated Sat Apr 29 11:23:54 CST 2017
     */
    private String useRule;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_coupon_info.GIVED_NUM
     *
     * @mbg.generated Sat Apr 29 11:23:54 CST 2017
     */
    private Long givedNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_coupon_info.USED_NUM
     *
     * @mbg.generated Sat Apr 29 11:23:54 CST 2017
     */
    private Long usedNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_coupon_info.TOTLE_NUM
     *
     * @mbg.generated Sat Apr 29 11:23:54 CST 2017
     */
    private Long totleNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_coupon_info.STATUS
     *
     * @mbg.generated Sat Apr 29 11:23:54 CST 2017
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_coupon_info.EXPIRE_TIME
     *
     * @mbg.generated Sat Apr 29 11:23:54 CST 2017
     */
    private Date expireTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_coupon_info.CREATE_ON
     *
     * @mbg.generated Sat Apr 29 11:23:54 CST 2017
     */
    private Date createOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_coupon_info.UPDATE_ON
     *
     * @mbg.generated Sat Apr 29 11:23:54 CST 2017
     */
    private Date updateOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_coupon_info.OPTIMIZED_LOCK
     *
     * @mbg.generated Sat Apr 29 11:23:54 CST 2017
     */
    private Integer optimizedLock;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_coupon_info.ID
     *
     * @return the value of ht_coupon_info.ID
     *
     * @mbg.generated Sat Apr 29 11:23:54 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_coupon_info.ID
     *
     * @param id the value for ht_coupon_info.ID
     *
     * @mbg.generated Sat Apr 29 11:23:54 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_coupon_info.NAME
     *
     * @return the value of ht_coupon_info.NAME
     *
     * @mbg.generated Sat Apr 29 11:23:54 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_coupon_info.NAME
     *
     * @param name the value for ht_coupon_info.NAME
     *
     * @mbg.generated Sat Apr 29 11:23:54 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_coupon_info.P_URL
     *
     * @return the value of ht_coupon_info.P_URL
     *
     * @mbg.generated Sat Apr 29 11:23:54 CST 2017
     */
    public String getpUrl() {
        return pUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_coupon_info.P_URL
     *
     * @param pUrl the value for ht_coupon_info.P_URL
     *
     * @mbg.generated Sat Apr 29 11:23:54 CST 2017
     */
    public void setpUrl(String pUrl) {
        this.pUrl = pUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_coupon_info.TYPE
     *
     * @return the value of ht_coupon_info.TYPE
     *
     * @mbg.generated Sat Apr 29 11:23:54 CST 2017
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_coupon_info.TYPE
     *
     * @param type the value for ht_coupon_info.TYPE
     *
     * @mbg.generated Sat Apr 29 11:23:54 CST 2017
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_coupon_info.C_DESC
     *
     * @return the value of ht_coupon_info.C_DESC
     *
     * @mbg.generated Sat Apr 29 11:23:54 CST 2017
     */
    public String getcDesc() {
        return cDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_coupon_info.C_DESC
     *
     * @param cDesc the value for ht_coupon_info.C_DESC
     *
     * @mbg.generated Sat Apr 29 11:23:54 CST 2017
     */
    public void setcDesc(String cDesc) {
        this.cDesc = cDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_coupon_info.AMT
     *
     * @return the value of ht_coupon_info.AMT
     *
     * @mbg.generated Sat Apr 29 11:23:54 CST 2017
     */
    public Double getAmt() {
        return amt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_coupon_info.AMT
     *
     * @param amt the value for ht_coupon_info.AMT
     *
     * @mbg.generated Sat Apr 29 11:23:54 CST 2017
     */
    public void setAmt(Double amt) {
        this.amt = amt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_coupon_info.MER_ID
     *
     * @return the value of ht_coupon_info.MER_ID
     *
     * @mbg.generated Sat Apr 29 11:23:54 CST 2017
     */
    public Long getMerId() {
        return merId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_coupon_info.MER_ID
     *
     * @param merId the value for ht_coupon_info.MER_ID
     *
     * @mbg.generated Sat Apr 29 11:23:54 CST 2017
     */
    public void setMerId(Long merId) {
        this.merId = merId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_coupon_info.AREA
     *
     * @return the value of ht_coupon_info.AREA
     *
     * @mbg.generated Sat Apr 29 11:23:54 CST 2017
     */
    public Integer getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_coupon_info.AREA
     *
     * @param area the value for ht_coupon_info.AREA
     *
     * @mbg.generated Sat Apr 29 11:23:54 CST 2017
     */
    public void setArea(Integer area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_coupon_info.USE_RULE
     *
     * @return the value of ht_coupon_info.USE_RULE
     *
     * @mbg.generated Sat Apr 29 11:23:54 CST 2017
     */
    public String getUseRule() {
        return useRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_coupon_info.USE_RULE
     *
     * @param useRule the value for ht_coupon_info.USE_RULE
     *
     * @mbg.generated Sat Apr 29 11:23:54 CST 2017
     */
    public void setUseRule(String useRule) {
        this.useRule = useRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_coupon_info.GIVED_NUM
     *
     * @return the value of ht_coupon_info.GIVED_NUM
     *
     * @mbg.generated Sat Apr 29 11:23:54 CST 2017
     */
    public Long getGivedNum() {
        return givedNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_coupon_info.GIVED_NUM
     *
     * @param givedNum the value for ht_coupon_info.GIVED_NUM
     *
     * @mbg.generated Sat Apr 29 11:23:54 CST 2017
     */
    public void setGivedNum(Long givedNum) {
        this.givedNum = givedNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_coupon_info.USED_NUM
     *
     * @return the value of ht_coupon_info.USED_NUM
     *
     * @mbg.generated Sat Apr 29 11:23:54 CST 2017
     */
    public Long getUsedNum() {
        return usedNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_coupon_info.USED_NUM
     *
     * @param usedNum the value for ht_coupon_info.USED_NUM
     *
     * @mbg.generated Sat Apr 29 11:23:54 CST 2017
     */
    public void setUsedNum(Long usedNum) {
        this.usedNum = usedNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_coupon_info.TOTLE_NUM
     *
     * @return the value of ht_coupon_info.TOTLE_NUM
     *
     * @mbg.generated Sat Apr 29 11:23:54 CST 2017
     */
    public Long getTotleNum() {
        return totleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_coupon_info.TOTLE_NUM
     *
     * @param totleNum the value for ht_coupon_info.TOTLE_NUM
     *
     * @mbg.generated Sat Apr 29 11:23:54 CST 2017
     */
    public void setTotleNum(Long totleNum) {
        this.totleNum = totleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_coupon_info.STATUS
     *
     * @return the value of ht_coupon_info.STATUS
     *
     * @mbg.generated Sat Apr 29 11:23:54 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_coupon_info.STATUS
     *
     * @param status the value for ht_coupon_info.STATUS
     *
     * @mbg.generated Sat Apr 29 11:23:54 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_coupon_info.EXPIRE_TIME
     *
     * @return the value of ht_coupon_info.EXPIRE_TIME
     *
     * @mbg.generated Sat Apr 29 11:23:54 CST 2017
     */
    public Date getExpireTime() {
        return expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_coupon_info.EXPIRE_TIME
     *
     * @param expireTime the value for ht_coupon_info.EXPIRE_TIME
     *
     * @mbg.generated Sat Apr 29 11:23:54 CST 2017
     */
    public void setExpireTime(Date expireTime) {
        this.expireTime = expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_coupon_info.CREATE_ON
     *
     * @return the value of ht_coupon_info.CREATE_ON
     *
     * @mbg.generated Sat Apr 29 11:23:54 CST 2017
     */
    public Date getCreateOn() {
        return createOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_coupon_info.CREATE_ON
     *
     * @param createOn the value for ht_coupon_info.CREATE_ON
     *
     * @mbg.generated Sat Apr 29 11:23:54 CST 2017
     */
    public void setCreateOn(Date createOn) {
        this.createOn = createOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_coupon_info.UPDATE_ON
     *
     * @return the value of ht_coupon_info.UPDATE_ON
     *
     * @mbg.generated Sat Apr 29 11:23:54 CST 2017
     */
    public Date getUpdateOn() {
        return updateOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_coupon_info.UPDATE_ON
     *
     * @param updateOn the value for ht_coupon_info.UPDATE_ON
     *
     * @mbg.generated Sat Apr 29 11:23:54 CST 2017
     */
    public void setUpdateOn(Date updateOn) {
        this.updateOn = updateOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_coupon_info.OPTIMIZED_LOCK
     *
     * @return the value of ht_coupon_info.OPTIMIZED_LOCK
     *
     * @mbg.generated Sat Apr 29 11:23:54 CST 2017
     */
    public Integer getOptimizedLock() {
        return optimizedLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_coupon_info.OPTIMIZED_LOCK
     *
     * @param optimizedLock the value for ht_coupon_info.OPTIMIZED_LOCK
     *
     * @mbg.generated Sat Apr 29 11:23:54 CST 2017
     */
    public void setOptimizedLock(Integer optimizedLock) {
        this.optimizedLock = optimizedLock;
    }
}