package com.partner.hlife.pojo;

import java.util.Date;

public class HtCoreModule {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_core_module.ID
     *
     * @mbg.generated Fri Apr 28 08:51:56 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_core_module.M_NAME
     *
     * @mbg.generated Fri Apr 28 08:51:56 CST 2017
     */
    private String mName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_core_module.P_URL
     *
     * @mbg.generated Fri Apr 28 08:51:56 CST 2017
     */
    private String pUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_core_module.M_ORDER
     *
     * @mbg.generated Fri Apr 28 08:51:56 CST 2017
     */
    private Integer mOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_core_module.URL
     *
     * @mbg.generated Fri Apr 28 08:51:56 CST 2017
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_core_module.CREATE_ON
     *
     * @mbg.generated Fri Apr 28 08:51:56 CST 2017
     */
    private Date createOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_core_module.UPDATE_ON
     *
     * @mbg.generated Fri Apr 28 08:51:56 CST 2017
     */
    private Date updateOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_core_module.OPTIMIZED_LOCK
     *
     * @mbg.generated Fri Apr 28 08:51:56 CST 2017
     */
    private Integer optimizedLock;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_core_module.ID
     *
     * @return the value of ht_core_module.ID
     *
     * @mbg.generated Fri Apr 28 08:51:56 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_core_module.ID
     *
     * @param id the value for ht_core_module.ID
     *
     * @mbg.generated Fri Apr 28 08:51:56 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_core_module.M_NAME
     *
     * @return the value of ht_core_module.M_NAME
     *
     * @mbg.generated Fri Apr 28 08:51:56 CST 2017
     */
    public String getmName() {
        return mName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_core_module.M_NAME
     *
     * @param mName the value for ht_core_module.M_NAME
     *
     * @mbg.generated Fri Apr 28 08:51:56 CST 2017
     */
    public void setmName(String mName) {
        this.mName = mName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_core_module.P_URL
     *
     * @return the value of ht_core_module.P_URL
     *
     * @mbg.generated Fri Apr 28 08:51:56 CST 2017
     */
    public String getpUrl() {
        return pUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_core_module.P_URL
     *
     * @param pUrl the value for ht_core_module.P_URL
     *
     * @mbg.generated Fri Apr 28 08:51:56 CST 2017
     */
    public void setpUrl(String pUrl) {
        this.pUrl = pUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_core_module.M_ORDER
     *
     * @return the value of ht_core_module.M_ORDER
     *
     * @mbg.generated Fri Apr 28 08:51:56 CST 2017
     */
    public Integer getmOrder() {
        return mOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_core_module.M_ORDER
     *
     * @param mOrder the value for ht_core_module.M_ORDER
     *
     * @mbg.generated Fri Apr 28 08:51:56 CST 2017
     */
    public void setmOrder(Integer mOrder) {
        this.mOrder = mOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_core_module.URL
     *
     * @return the value of ht_core_module.URL
     *
     * @mbg.generated Fri Apr 28 08:51:56 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_core_module.URL
     *
     * @param url the value for ht_core_module.URL
     *
     * @mbg.generated Fri Apr 28 08:51:56 CST 2017
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_core_module.CREATE_ON
     *
     * @return the value of ht_core_module.CREATE_ON
     *
     * @mbg.generated Fri Apr 28 08:51:56 CST 2017
     */
    public Date getCreateOn() {
        return createOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_core_module.CREATE_ON
     *
     * @param createOn the value for ht_core_module.CREATE_ON
     *
     * @mbg.generated Fri Apr 28 08:51:56 CST 2017
     */
    public void setCreateOn(Date createOn) {
        this.createOn = createOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_core_module.UPDATE_ON
     *
     * @return the value of ht_core_module.UPDATE_ON
     *
     * @mbg.generated Fri Apr 28 08:51:56 CST 2017
     */
    public Date getUpdateOn() {
        return updateOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_core_module.UPDATE_ON
     *
     * @param updateOn the value for ht_core_module.UPDATE_ON
     *
     * @mbg.generated Fri Apr 28 08:51:56 CST 2017
     */
    public void setUpdateOn(Date updateOn) {
        this.updateOn = updateOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_core_module.OPTIMIZED_LOCK
     *
     * @return the value of ht_core_module.OPTIMIZED_LOCK
     *
     * @mbg.generated Fri Apr 28 08:51:56 CST 2017
     */
    public Integer getOptimizedLock() {
        return optimizedLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_core_module.OPTIMIZED_LOCK
     *
     * @param optimizedLock the value for ht_core_module.OPTIMIZED_LOCK
     *
     * @mbg.generated Fri Apr 28 08:51:56 CST 2017
     */
    public void setOptimizedLock(Integer optimizedLock) {
        this.optimizedLock = optimizedLock;
    }
}