package com.partner.hlife.pojo;

import java.util.Date;

public class HtFrontPage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_front_page.ID
     *
     * @mbg.generated Fri Apr 28 08:33:30 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_front_page.TITLE
     *
     * @mbg.generated Fri Apr 28 08:33:30 CST 2017
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_front_page.CONTENT
     *
     * @mbg.generated Fri Apr 28 08:33:30 CST 2017
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_front_page.STATUS
     *
     * @mbg.generated Fri Apr 28 08:33:30 CST 2017
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_front_page.AREA
     *
     * @mbg.generated Fri Apr 28 08:33:30 CST 2017
     */
    private Integer area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_front_page.CREATE_ON
     *
     * @mbg.generated Fri Apr 28 08:33:30 CST 2017
     */
    private Date createOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_front_page.UPDATE_ON
     *
     * @mbg.generated Fri Apr 28 08:33:30 CST 2017
     */
    private Date updateOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_front_page.OPTIMIZED_LOCK
     *
     * @mbg.generated Fri Apr 28 08:33:30 CST 2017
     */
    private Integer optimizedLock;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_front_page.ID
     *
     * @return the value of ht_front_page.ID
     *
     * @mbg.generated Fri Apr 28 08:33:30 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_front_page.ID
     *
     * @param id the value for ht_front_page.ID
     *
     * @mbg.generated Fri Apr 28 08:33:30 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_front_page.TITLE
     *
     * @return the value of ht_front_page.TITLE
     *
     * @mbg.generated Fri Apr 28 08:33:30 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_front_page.TITLE
     *
     * @param title the value for ht_front_page.TITLE
     *
     * @mbg.generated Fri Apr 28 08:33:30 CST 2017
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_front_page.CONTENT
     *
     * @return the value of ht_front_page.CONTENT
     *
     * @mbg.generated Fri Apr 28 08:33:30 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_front_page.CONTENT
     *
     * @param content the value for ht_front_page.CONTENT
     *
     * @mbg.generated Fri Apr 28 08:33:30 CST 2017
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_front_page.STATUS
     *
     * @return the value of ht_front_page.STATUS
     *
     * @mbg.generated Fri Apr 28 08:33:30 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_front_page.STATUS
     *
     * @param status the value for ht_front_page.STATUS
     *
     * @mbg.generated Fri Apr 28 08:33:30 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_front_page.AREA
     *
     * @return the value of ht_front_page.AREA
     *
     * @mbg.generated Fri Apr 28 08:33:30 CST 2017
     */
    public Integer getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_front_page.AREA
     *
     * @param area the value for ht_front_page.AREA
     *
     * @mbg.generated Fri Apr 28 08:33:30 CST 2017
     */
    public void setArea(Integer area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_front_page.CREATE_ON
     *
     * @return the value of ht_front_page.CREATE_ON
     *
     * @mbg.generated Fri Apr 28 08:33:30 CST 2017
     */
    public Date getCreateOn() {
        return createOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_front_page.CREATE_ON
     *
     * @param createOn the value for ht_front_page.CREATE_ON
     *
     * @mbg.generated Fri Apr 28 08:33:30 CST 2017
     */
    public void setCreateOn(Date createOn) {
        this.createOn = createOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_front_page.UPDATE_ON
     *
     * @return the value of ht_front_page.UPDATE_ON
     *
     * @mbg.generated Fri Apr 28 08:33:30 CST 2017
     */
    public Date getUpdateOn() {
        return updateOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_front_page.UPDATE_ON
     *
     * @param updateOn the value for ht_front_page.UPDATE_ON
     *
     * @mbg.generated Fri Apr 28 08:33:30 CST 2017
     */
    public void setUpdateOn(Date updateOn) {
        this.updateOn = updateOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_front_page.OPTIMIZED_LOCK
     *
     * @return the value of ht_front_page.OPTIMIZED_LOCK
     *
     * @mbg.generated Fri Apr 28 08:33:30 CST 2017
     */
    public Integer getOptimizedLock() {
        return optimizedLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_front_page.OPTIMIZED_LOCK
     *
     * @param optimizedLock the value for ht_front_page.OPTIMIZED_LOCK
     *
     * @mbg.generated Fri Apr 28 08:33:30 CST 2017
     */
    public void setOptimizedLock(Integer optimizedLock) {
        this.optimizedLock = optimizedLock;
    }
}