package com.partner.hlife.pojo;

import java.util.Date;

public class HtMerPhoto {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_mer_photo.ID
     *
     * @mbg.generated Fri Apr 28 09:32:24 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_mer_photo.MER_ID
     *
     * @mbg.generated Fri Apr 28 09:32:24 CST 2017
     */
    private Long merId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_mer_photo.P_ULR
     *
     * @mbg.generated Fri Apr 28 09:32:24 CST 2017
     */
    private String pUlr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_mer_photo.P_ORDER
     *
     * @mbg.generated Fri Apr 28 09:32:24 CST 2017
     */
    private Short pOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_mer_photo.CREATE_ON
     *
     * @mbg.generated Fri Apr 28 09:32:24 CST 2017
     */
    private Date createOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_mer_photo.UPDATE_ON
     *
     * @mbg.generated Fri Apr 28 09:32:24 CST 2017
     */
    private Date updateOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_mer_photo.OPTIMIZED_LOCK
     *
     * @mbg.generated Fri Apr 28 09:32:24 CST 2017
     */
    private Integer optimizedLock;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_mer_photo.ID
     *
     * @return the value of ht_mer_photo.ID
     *
     * @mbg.generated Fri Apr 28 09:32:24 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_mer_photo.ID
     *
     * @param id the value for ht_mer_photo.ID
     *
     * @mbg.generated Fri Apr 28 09:32:24 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_mer_photo.MER_ID
     *
     * @return the value of ht_mer_photo.MER_ID
     *
     * @mbg.generated Fri Apr 28 09:32:24 CST 2017
     */
    public Long getMerId() {
        return merId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_mer_photo.MER_ID
     *
     * @param merId the value for ht_mer_photo.MER_ID
     *
     * @mbg.generated Fri Apr 28 09:32:24 CST 2017
     */
    public void setMerId(Long merId) {
        this.merId = merId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_mer_photo.P_ULR
     *
     * @return the value of ht_mer_photo.P_ULR
     *
     * @mbg.generated Fri Apr 28 09:32:24 CST 2017
     */
    public String getpUlr() {
        return pUlr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_mer_photo.P_ULR
     *
     * @param pUlr the value for ht_mer_photo.P_ULR
     *
     * @mbg.generated Fri Apr 28 09:32:24 CST 2017
     */
    public void setpUlr(String pUlr) {
        this.pUlr = pUlr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_mer_photo.P_ORDER
     *
     * @return the value of ht_mer_photo.P_ORDER
     *
     * @mbg.generated Fri Apr 28 09:32:24 CST 2017
     */
    public Short getpOrder() {
        return pOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_mer_photo.P_ORDER
     *
     * @param pOrder the value for ht_mer_photo.P_ORDER
     *
     * @mbg.generated Fri Apr 28 09:32:24 CST 2017
     */
    public void setpOrder(Short pOrder) {
        this.pOrder = pOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_mer_photo.CREATE_ON
     *
     * @return the value of ht_mer_photo.CREATE_ON
     *
     * @mbg.generated Fri Apr 28 09:32:24 CST 2017
     */
    public Date getCreateOn() {
        return createOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_mer_photo.CREATE_ON
     *
     * @param createOn the value for ht_mer_photo.CREATE_ON
     *
     * @mbg.generated Fri Apr 28 09:32:24 CST 2017
     */
    public void setCreateOn(Date createOn) {
        this.createOn = createOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_mer_photo.UPDATE_ON
     *
     * @return the value of ht_mer_photo.UPDATE_ON
     *
     * @mbg.generated Fri Apr 28 09:32:24 CST 2017
     */
    public Date getUpdateOn() {
        return updateOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_mer_photo.UPDATE_ON
     *
     * @param updateOn the value for ht_mer_photo.UPDATE_ON
     *
     * @mbg.generated Fri Apr 28 09:32:24 CST 2017
     */
    public void setUpdateOn(Date updateOn) {
        this.updateOn = updateOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_mer_photo.OPTIMIZED_LOCK
     *
     * @return the value of ht_mer_photo.OPTIMIZED_LOCK
     *
     * @mbg.generated Fri Apr 28 09:32:24 CST 2017
     */
    public Integer getOptimizedLock() {
        return optimizedLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_mer_photo.OPTIMIZED_LOCK
     *
     * @param optimizedLock the value for ht_mer_photo.OPTIMIZED_LOCK
     *
     * @mbg.generated Fri Apr 28 09:32:24 CST 2017
     */
    public void setOptimizedLock(Integer optimizedLock) {
        this.optimizedLock = optimizedLock;
    }
}