package com.partner.hlife.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class HtMerchantInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ht_merchant_info
     *
     * @mbg.generated Fri Apr 28 09:47:45 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ht_merchant_info
     *
     * @mbg.generated Fri Apr 28 09:47:45 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ht_merchant_info
     *
     * @mbg.generated Fri Apr 28 09:47:45 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ht_merchant_info
     *
     * @mbg.generated Fri Apr 28 09:47:45 CST 2017
     */
    public HtMerchantInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ht_merchant_info
     *
     * @mbg.generated Fri Apr 28 09:47:45 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ht_merchant_info
     *
     * @mbg.generated Fri Apr 28 09:47:45 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ht_merchant_info
     *
     * @mbg.generated Fri Apr 28 09:47:45 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ht_merchant_info
     *
     * @mbg.generated Fri Apr 28 09:47:45 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ht_merchant_info
     *
     * @mbg.generated Fri Apr 28 09:47:45 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ht_merchant_info
     *
     * @mbg.generated Fri Apr 28 09:47:45 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ht_merchant_info
     *
     * @mbg.generated Fri Apr 28 09:47:45 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ht_merchant_info
     *
     * @mbg.generated Fri Apr 28 09:47:45 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ht_merchant_info
     *
     * @mbg.generated Fri Apr 28 09:47:45 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ht_merchant_info
     *
     * @mbg.generated Fri Apr 28 09:47:45 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ht_merchant_info
     *
     * @mbg.generated Fri Apr 28 09:47:45 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSerTyepIsNull() {
            addCriterion("SER_TYEP is null");
            return (Criteria) this;
        }

        public Criteria andSerTyepIsNotNull() {
            addCriterion("SER_TYEP is not null");
            return (Criteria) this;
        }

        public Criteria andSerTyepEqualTo(Integer value) {
            addCriterion("SER_TYEP =", value, "serTyep");
            return (Criteria) this;
        }

        public Criteria andSerTyepNotEqualTo(Integer value) {
            addCriterion("SER_TYEP <>", value, "serTyep");
            return (Criteria) this;
        }

        public Criteria andSerTyepGreaterThan(Integer value) {
            addCriterion("SER_TYEP >", value, "serTyep");
            return (Criteria) this;
        }

        public Criteria andSerTyepGreaterThanOrEqualTo(Integer value) {
            addCriterion("SER_TYEP >=", value, "serTyep");
            return (Criteria) this;
        }

        public Criteria andSerTyepLessThan(Integer value) {
            addCriterion("SER_TYEP <", value, "serTyep");
            return (Criteria) this;
        }

        public Criteria andSerTyepLessThanOrEqualTo(Integer value) {
            addCriterion("SER_TYEP <=", value, "serTyep");
            return (Criteria) this;
        }

        public Criteria andSerTyepIn(List<Integer> values) {
            addCriterion("SER_TYEP in", values, "serTyep");
            return (Criteria) this;
        }

        public Criteria andSerTyepNotIn(List<Integer> values) {
            addCriterion("SER_TYEP not in", values, "serTyep");
            return (Criteria) this;
        }

        public Criteria andSerTyepBetween(Integer value1, Integer value2) {
            addCriterion("SER_TYEP between", value1, value2, "serTyep");
            return (Criteria) this;
        }

        public Criteria andSerTyepNotBetween(Integer value1, Integer value2) {
            addCriterion("SER_TYEP not between", value1, value2, "serTyep");
            return (Criteria) this;
        }

        public Criteria andMNameIsNull() {
            addCriterion("M_NAME is null");
            return (Criteria) this;
        }

        public Criteria andMNameIsNotNull() {
            addCriterion("M_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andMNameEqualTo(String value) {
            addCriterion("M_NAME =", value, "mName");
            return (Criteria) this;
        }

        public Criteria andMNameNotEqualTo(String value) {
            addCriterion("M_NAME <>", value, "mName");
            return (Criteria) this;
        }

        public Criteria andMNameGreaterThan(String value) {
            addCriterion("M_NAME >", value, "mName");
            return (Criteria) this;
        }

        public Criteria andMNameGreaterThanOrEqualTo(String value) {
            addCriterion("M_NAME >=", value, "mName");
            return (Criteria) this;
        }

        public Criteria andMNameLessThan(String value) {
            addCriterion("M_NAME <", value, "mName");
            return (Criteria) this;
        }

        public Criteria andMNameLessThanOrEqualTo(String value) {
            addCriterion("M_NAME <=", value, "mName");
            return (Criteria) this;
        }

        public Criteria andMNameLike(String value) {
            addCriterion("M_NAME like", value, "mName");
            return (Criteria) this;
        }

        public Criteria andMNameNotLike(String value) {
            addCriterion("M_NAME not like", value, "mName");
            return (Criteria) this;
        }

        public Criteria andMNameIn(List<String> values) {
            addCriterion("M_NAME in", values, "mName");
            return (Criteria) this;
        }

        public Criteria andMNameNotIn(List<String> values) {
            addCriterion("M_NAME not in", values, "mName");
            return (Criteria) this;
        }

        public Criteria andMNameBetween(String value1, String value2) {
            addCriterion("M_NAME between", value1, value2, "mName");
            return (Criteria) this;
        }

        public Criteria andMNameNotBetween(String value1, String value2) {
            addCriterion("M_NAME not between", value1, value2, "mName");
            return (Criteria) this;
        }

        public Criteria andMAddressIsNull() {
            addCriterion("M_ADDRESS is null");
            return (Criteria) this;
        }

        public Criteria andMAddressIsNotNull() {
            addCriterion("M_ADDRESS is not null");
            return (Criteria) this;
        }

        public Criteria andMAddressEqualTo(String value) {
            addCriterion("M_ADDRESS =", value, "mAddress");
            return (Criteria) this;
        }

        public Criteria andMAddressNotEqualTo(String value) {
            addCriterion("M_ADDRESS <>", value, "mAddress");
            return (Criteria) this;
        }

        public Criteria andMAddressGreaterThan(String value) {
            addCriterion("M_ADDRESS >", value, "mAddress");
            return (Criteria) this;
        }

        public Criteria andMAddressGreaterThanOrEqualTo(String value) {
            addCriterion("M_ADDRESS >=", value, "mAddress");
            return (Criteria) this;
        }

        public Criteria andMAddressLessThan(String value) {
            addCriterion("M_ADDRESS <", value, "mAddress");
            return (Criteria) this;
        }

        public Criteria andMAddressLessThanOrEqualTo(String value) {
            addCriterion("M_ADDRESS <=", value, "mAddress");
            return (Criteria) this;
        }

        public Criteria andMAddressLike(String value) {
            addCriterion("M_ADDRESS like", value, "mAddress");
            return (Criteria) this;
        }

        public Criteria andMAddressNotLike(String value) {
            addCriterion("M_ADDRESS not like", value, "mAddress");
            return (Criteria) this;
        }

        public Criteria andMAddressIn(List<String> values) {
            addCriterion("M_ADDRESS in", values, "mAddress");
            return (Criteria) this;
        }

        public Criteria andMAddressNotIn(List<String> values) {
            addCriterion("M_ADDRESS not in", values, "mAddress");
            return (Criteria) this;
        }

        public Criteria andMAddressBetween(String value1, String value2) {
            addCriterion("M_ADDRESS between", value1, value2, "mAddress");
            return (Criteria) this;
        }

        public Criteria andMAddressNotBetween(String value1, String value2) {
            addCriterion("M_ADDRESS not between", value1, value2, "mAddress");
            return (Criteria) this;
        }

        public Criteria andInfoIsNull() {
            addCriterion("INFO is null");
            return (Criteria) this;
        }

        public Criteria andInfoIsNotNull() {
            addCriterion("INFO is not null");
            return (Criteria) this;
        }

        public Criteria andInfoEqualTo(String value) {
            addCriterion("INFO =", value, "info");
            return (Criteria) this;
        }

        public Criteria andInfoNotEqualTo(String value) {
            addCriterion("INFO <>", value, "info");
            return (Criteria) this;
        }

        public Criteria andInfoGreaterThan(String value) {
            addCriterion("INFO >", value, "info");
            return (Criteria) this;
        }

        public Criteria andInfoGreaterThanOrEqualTo(String value) {
            addCriterion("INFO >=", value, "info");
            return (Criteria) this;
        }

        public Criteria andInfoLessThan(String value) {
            addCriterion("INFO <", value, "info");
            return (Criteria) this;
        }

        public Criteria andInfoLessThanOrEqualTo(String value) {
            addCriterion("INFO <=", value, "info");
            return (Criteria) this;
        }

        public Criteria andInfoLike(String value) {
            addCriterion("INFO like", value, "info");
            return (Criteria) this;
        }

        public Criteria andInfoNotLike(String value) {
            addCriterion("INFO not like", value, "info");
            return (Criteria) this;
        }

        public Criteria andInfoIn(List<String> values) {
            addCriterion("INFO in", values, "info");
            return (Criteria) this;
        }

        public Criteria andInfoNotIn(List<String> values) {
            addCriterion("INFO not in", values, "info");
            return (Criteria) this;
        }

        public Criteria andInfoBetween(String value1, String value2) {
            addCriterion("INFO between", value1, value2, "info");
            return (Criteria) this;
        }

        public Criteria andInfoNotBetween(String value1, String value2) {
            addCriterion("INFO not between", value1, value2, "info");
            return (Criteria) this;
        }

        public Criteria andMDescIsNull() {
            addCriterion("M_DESC is null");
            return (Criteria) this;
        }

        public Criteria andMDescIsNotNull() {
            addCriterion("M_DESC is not null");
            return (Criteria) this;
        }

        public Criteria andMDescEqualTo(String value) {
            addCriterion("M_DESC =", value, "mDesc");
            return (Criteria) this;
        }

        public Criteria andMDescNotEqualTo(String value) {
            addCriterion("M_DESC <>", value, "mDesc");
            return (Criteria) this;
        }

        public Criteria andMDescGreaterThan(String value) {
            addCriterion("M_DESC >", value, "mDesc");
            return (Criteria) this;
        }

        public Criteria andMDescGreaterThanOrEqualTo(String value) {
            addCriterion("M_DESC >=", value, "mDesc");
            return (Criteria) this;
        }

        public Criteria andMDescLessThan(String value) {
            addCriterion("M_DESC <", value, "mDesc");
            return (Criteria) this;
        }

        public Criteria andMDescLessThanOrEqualTo(String value) {
            addCriterion("M_DESC <=", value, "mDesc");
            return (Criteria) this;
        }

        public Criteria andMDescLike(String value) {
            addCriterion("M_DESC like", value, "mDesc");
            return (Criteria) this;
        }

        public Criteria andMDescNotLike(String value) {
            addCriterion("M_DESC not like", value, "mDesc");
            return (Criteria) this;
        }

        public Criteria andMDescIn(List<String> values) {
            addCriterion("M_DESC in", values, "mDesc");
            return (Criteria) this;
        }

        public Criteria andMDescNotIn(List<String> values) {
            addCriterion("M_DESC not in", values, "mDesc");
            return (Criteria) this;
        }

        public Criteria andMDescBetween(String value1, String value2) {
            addCriterion("M_DESC between", value1, value2, "mDesc");
            return (Criteria) this;
        }

        public Criteria andMDescNotBetween(String value1, String value2) {
            addCriterion("M_DESC not between", value1, value2, "mDesc");
            return (Criteria) this;
        }

        public Criteria andLogoUrlIsNull() {
            addCriterion("LOGO_URL is null");
            return (Criteria) this;
        }

        public Criteria andLogoUrlIsNotNull() {
            addCriterion("LOGO_URL is not null");
            return (Criteria) this;
        }

        public Criteria andLogoUrlEqualTo(String value) {
            addCriterion("LOGO_URL =", value, "logoUrl");
            return (Criteria) this;
        }

        public Criteria andLogoUrlNotEqualTo(String value) {
            addCriterion("LOGO_URL <>", value, "logoUrl");
            return (Criteria) this;
        }

        public Criteria andLogoUrlGreaterThan(String value) {
            addCriterion("LOGO_URL >", value, "logoUrl");
            return (Criteria) this;
        }

        public Criteria andLogoUrlGreaterThanOrEqualTo(String value) {
            addCriterion("LOGO_URL >=", value, "logoUrl");
            return (Criteria) this;
        }

        public Criteria andLogoUrlLessThan(String value) {
            addCriterion("LOGO_URL <", value, "logoUrl");
            return (Criteria) this;
        }

        public Criteria andLogoUrlLessThanOrEqualTo(String value) {
            addCriterion("LOGO_URL <=", value, "logoUrl");
            return (Criteria) this;
        }

        public Criteria andLogoUrlLike(String value) {
            addCriterion("LOGO_URL like", value, "logoUrl");
            return (Criteria) this;
        }

        public Criteria andLogoUrlNotLike(String value) {
            addCriterion("LOGO_URL not like", value, "logoUrl");
            return (Criteria) this;
        }

        public Criteria andLogoUrlIn(List<String> values) {
            addCriterion("LOGO_URL in", values, "logoUrl");
            return (Criteria) this;
        }

        public Criteria andLogoUrlNotIn(List<String> values) {
            addCriterion("LOGO_URL not in", values, "logoUrl");
            return (Criteria) this;
        }

        public Criteria andLogoUrlBetween(String value1, String value2) {
            addCriterion("LOGO_URL between", value1, value2, "logoUrl");
            return (Criteria) this;
        }

        public Criteria andLogoUrlNotBetween(String value1, String value2) {
            addCriterion("LOGO_URL not between", value1, value2, "logoUrl");
            return (Criteria) this;
        }

        public Criteria andPwdIsNull() {
            addCriterion("PWD is null");
            return (Criteria) this;
        }

        public Criteria andPwdIsNotNull() {
            addCriterion("PWD is not null");
            return (Criteria) this;
        }

        public Criteria andPwdEqualTo(String value) {
            addCriterion("PWD =", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdNotEqualTo(String value) {
            addCriterion("PWD <>", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdGreaterThan(String value) {
            addCriterion("PWD >", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdGreaterThanOrEqualTo(String value) {
            addCriterion("PWD >=", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdLessThan(String value) {
            addCriterion("PWD <", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdLessThanOrEqualTo(String value) {
            addCriterion("PWD <=", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdLike(String value) {
            addCriterion("PWD like", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdNotLike(String value) {
            addCriterion("PWD not like", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdIn(List<String> values) {
            addCriterion("PWD in", values, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdNotIn(List<String> values) {
            addCriterion("PWD not in", values, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdBetween(String value1, String value2) {
            addCriterion("PWD between", value1, value2, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdNotBetween(String value1, String value2) {
            addCriterion("PWD not between", value1, value2, "pwd");
            return (Criteria) this;
        }

        public Criteria andMobileIsNull() {
            addCriterion("MOBILE is null");
            return (Criteria) this;
        }

        public Criteria andMobileIsNotNull() {
            addCriterion("MOBILE is not null");
            return (Criteria) this;
        }

        public Criteria andMobileEqualTo(String value) {
            addCriterion("MOBILE =", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotEqualTo(String value) {
            addCriterion("MOBILE <>", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThan(String value) {
            addCriterion("MOBILE >", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThanOrEqualTo(String value) {
            addCriterion("MOBILE >=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThan(String value) {
            addCriterion("MOBILE <", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThanOrEqualTo(String value) {
            addCriterion("MOBILE <=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLike(String value) {
            addCriterion("MOBILE like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotLike(String value) {
            addCriterion("MOBILE not like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileIn(List<String> values) {
            addCriterion("MOBILE in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotIn(List<String> values) {
            addCriterion("MOBILE not in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileBetween(String value1, String value2) {
            addCriterion("MOBILE between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotBetween(String value1, String value2) {
            addCriterion("MOBILE not between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andAreaIsNull() {
            addCriterion("AREA is null");
            return (Criteria) this;
        }

        public Criteria andAreaIsNotNull() {
            addCriterion("AREA is not null");
            return (Criteria) this;
        }

        public Criteria andAreaEqualTo(Integer value) {
            addCriterion("AREA =", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotEqualTo(Integer value) {
            addCriterion("AREA <>", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaGreaterThan(Integer value) {
            addCriterion("AREA >", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaGreaterThanOrEqualTo(Integer value) {
            addCriterion("AREA >=", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLessThan(Integer value) {
            addCriterion("AREA <", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLessThanOrEqualTo(Integer value) {
            addCriterion("AREA <=", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaIn(List<Integer> values) {
            addCriterion("AREA in", values, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotIn(List<Integer> values) {
            addCriterion("AREA not in", values, "area");
            return (Criteria) this;
        }

        public Criteria andAreaBetween(Integer value1, Integer value2) {
            addCriterion("AREA between", value1, value2, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotBetween(Integer value1, Integer value2) {
            addCriterion("AREA not between", value1, value2, "area");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Byte value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Byte value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Byte value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Byte value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Byte value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Byte> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Byte> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Byte value1, Byte value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andMarkNumIsNull() {
            addCriterion("MARK_NUM is null");
            return (Criteria) this;
        }

        public Criteria andMarkNumIsNotNull() {
            addCriterion("MARK_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andMarkNumEqualTo(Long value) {
            addCriterion("MARK_NUM =", value, "markNum");
            return (Criteria) this;
        }

        public Criteria andMarkNumNotEqualTo(Long value) {
            addCriterion("MARK_NUM <>", value, "markNum");
            return (Criteria) this;
        }

        public Criteria andMarkNumGreaterThan(Long value) {
            addCriterion("MARK_NUM >", value, "markNum");
            return (Criteria) this;
        }

        public Criteria andMarkNumGreaterThanOrEqualTo(Long value) {
            addCriterion("MARK_NUM >=", value, "markNum");
            return (Criteria) this;
        }

        public Criteria andMarkNumLessThan(Long value) {
            addCriterion("MARK_NUM <", value, "markNum");
            return (Criteria) this;
        }

        public Criteria andMarkNumLessThanOrEqualTo(Long value) {
            addCriterion("MARK_NUM <=", value, "markNum");
            return (Criteria) this;
        }

        public Criteria andMarkNumIn(List<Long> values) {
            addCriterion("MARK_NUM in", values, "markNum");
            return (Criteria) this;
        }

        public Criteria andMarkNumNotIn(List<Long> values) {
            addCriterion("MARK_NUM not in", values, "markNum");
            return (Criteria) this;
        }

        public Criteria andMarkNumBetween(Long value1, Long value2) {
            addCriterion("MARK_NUM between", value1, value2, "markNum");
            return (Criteria) this;
        }

        public Criteria andMarkNumNotBetween(Long value1, Long value2) {
            addCriterion("MARK_NUM not between", value1, value2, "markNum");
            return (Criteria) this;
        }

        public Criteria andCoordIsNull() {
            addCriterion("COORD is null");
            return (Criteria) this;
        }

        public Criteria andCoordIsNotNull() {
            addCriterion("COORD is not null");
            return (Criteria) this;
        }

        public Criteria andCoordEqualTo(String value) {
            addCriterion("COORD =", value, "coord");
            return (Criteria) this;
        }

        public Criteria andCoordNotEqualTo(String value) {
            addCriterion("COORD <>", value, "coord");
            return (Criteria) this;
        }

        public Criteria andCoordGreaterThan(String value) {
            addCriterion("COORD >", value, "coord");
            return (Criteria) this;
        }

        public Criteria andCoordGreaterThanOrEqualTo(String value) {
            addCriterion("COORD >=", value, "coord");
            return (Criteria) this;
        }

        public Criteria andCoordLessThan(String value) {
            addCriterion("COORD <", value, "coord");
            return (Criteria) this;
        }

        public Criteria andCoordLessThanOrEqualTo(String value) {
            addCriterion("COORD <=", value, "coord");
            return (Criteria) this;
        }

        public Criteria andCoordLike(String value) {
            addCriterion("COORD like", value, "coord");
            return (Criteria) this;
        }

        public Criteria andCoordNotLike(String value) {
            addCriterion("COORD not like", value, "coord");
            return (Criteria) this;
        }

        public Criteria andCoordIn(List<String> values) {
            addCriterion("COORD in", values, "coord");
            return (Criteria) this;
        }

        public Criteria andCoordNotIn(List<String> values) {
            addCriterion("COORD not in", values, "coord");
            return (Criteria) this;
        }

        public Criteria andCoordBetween(String value1, String value2) {
            addCriterion("COORD between", value1, value2, "coord");
            return (Criteria) this;
        }

        public Criteria andCoordNotBetween(String value1, String value2) {
            addCriterion("COORD not between", value1, value2, "coord");
            return (Criteria) this;
        }

        public Criteria andCreateOnIsNull() {
            addCriterion("CREATE_ON is null");
            return (Criteria) this;
        }

        public Criteria andCreateOnIsNotNull() {
            addCriterion("CREATE_ON is not null");
            return (Criteria) this;
        }

        public Criteria andCreateOnEqualTo(Date value) {
            addCriterionForJDBCDate("CREATE_ON =", value, "createOn");
            return (Criteria) this;
        }

        public Criteria andCreateOnNotEqualTo(Date value) {
            addCriterionForJDBCDate("CREATE_ON <>", value, "createOn");
            return (Criteria) this;
        }

        public Criteria andCreateOnGreaterThan(Date value) {
            addCriterionForJDBCDate("CREATE_ON >", value, "createOn");
            return (Criteria) this;
        }

        public Criteria andCreateOnGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("CREATE_ON >=", value, "createOn");
            return (Criteria) this;
        }

        public Criteria andCreateOnLessThan(Date value) {
            addCriterionForJDBCDate("CREATE_ON <", value, "createOn");
            return (Criteria) this;
        }

        public Criteria andCreateOnLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("CREATE_ON <=", value, "createOn");
            return (Criteria) this;
        }

        public Criteria andCreateOnIn(List<Date> values) {
            addCriterionForJDBCDate("CREATE_ON in", values, "createOn");
            return (Criteria) this;
        }

        public Criteria andCreateOnNotIn(List<Date> values) {
            addCriterionForJDBCDate("CREATE_ON not in", values, "createOn");
            return (Criteria) this;
        }

        public Criteria andCreateOnBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("CREATE_ON between", value1, value2, "createOn");
            return (Criteria) this;
        }

        public Criteria andCreateOnNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("CREATE_ON not between", value1, value2, "createOn");
            return (Criteria) this;
        }

        public Criteria andUpdateOnIsNull() {
            addCriterion("UPDATE_ON is null");
            return (Criteria) this;
        }

        public Criteria andUpdateOnIsNotNull() {
            addCriterion("UPDATE_ON is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateOnEqualTo(Date value) {
            addCriterionForJDBCDate("UPDATE_ON =", value, "updateOn");
            return (Criteria) this;
        }

        public Criteria andUpdateOnNotEqualTo(Date value) {
            addCriterionForJDBCDate("UPDATE_ON <>", value, "updateOn");
            return (Criteria) this;
        }

        public Criteria andUpdateOnGreaterThan(Date value) {
            addCriterionForJDBCDate("UPDATE_ON >", value, "updateOn");
            return (Criteria) this;
        }

        public Criteria andUpdateOnGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("UPDATE_ON >=", value, "updateOn");
            return (Criteria) this;
        }

        public Criteria andUpdateOnLessThan(Date value) {
            addCriterionForJDBCDate("UPDATE_ON <", value, "updateOn");
            return (Criteria) this;
        }

        public Criteria andUpdateOnLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("UPDATE_ON <=", value, "updateOn");
            return (Criteria) this;
        }

        public Criteria andUpdateOnIn(List<Date> values) {
            addCriterionForJDBCDate("UPDATE_ON in", values, "updateOn");
            return (Criteria) this;
        }

        public Criteria andUpdateOnNotIn(List<Date> values) {
            addCriterionForJDBCDate("UPDATE_ON not in", values, "updateOn");
            return (Criteria) this;
        }

        public Criteria andUpdateOnBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("UPDATE_ON between", value1, value2, "updateOn");
            return (Criteria) this;
        }

        public Criteria andUpdateOnNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("UPDATE_ON not between", value1, value2, "updateOn");
            return (Criteria) this;
        }

        public Criteria andOptimizedLockIsNull() {
            addCriterion("OPTIMIZED_LOCK is null");
            return (Criteria) this;
        }

        public Criteria andOptimizedLockIsNotNull() {
            addCriterion("OPTIMIZED_LOCK is not null");
            return (Criteria) this;
        }

        public Criteria andOptimizedLockEqualTo(Integer value) {
            addCriterion("OPTIMIZED_LOCK =", value, "optimizedLock");
            return (Criteria) this;
        }

        public Criteria andOptimizedLockNotEqualTo(Integer value) {
            addCriterion("OPTIMIZED_LOCK <>", value, "optimizedLock");
            return (Criteria) this;
        }

        public Criteria andOptimizedLockGreaterThan(Integer value) {
            addCriterion("OPTIMIZED_LOCK >", value, "optimizedLock");
            return (Criteria) this;
        }

        public Criteria andOptimizedLockGreaterThanOrEqualTo(Integer value) {
            addCriterion("OPTIMIZED_LOCK >=", value, "optimizedLock");
            return (Criteria) this;
        }

        public Criteria andOptimizedLockLessThan(Integer value) {
            addCriterion("OPTIMIZED_LOCK <", value, "optimizedLock");
            return (Criteria) this;
        }

        public Criteria andOptimizedLockLessThanOrEqualTo(Integer value) {
            addCriterion("OPTIMIZED_LOCK <=", value, "optimizedLock");
            return (Criteria) this;
        }

        public Criteria andOptimizedLockIn(List<Integer> values) {
            addCriterion("OPTIMIZED_LOCK in", values, "optimizedLock");
            return (Criteria) this;
        }

        public Criteria andOptimizedLockNotIn(List<Integer> values) {
            addCriterion("OPTIMIZED_LOCK not in", values, "optimizedLock");
            return (Criteria) this;
        }

        public Criteria andOptimizedLockBetween(Integer value1, Integer value2) {
            addCriterion("OPTIMIZED_LOCK between", value1, value2, "optimizedLock");
            return (Criteria) this;
        }

        public Criteria andOptimizedLockNotBetween(Integer value1, Integer value2) {
            addCriterion("OPTIMIZED_LOCK not between", value1, value2, "optimizedLock");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ht_merchant_info
     *
     * @mbg.generated do_not_delete_during_merge Fri Apr 28 09:47:45 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ht_merchant_info
     *
     * @mbg.generated Fri Apr 28 09:47:45 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}