package com.partner.hlife.pojo;

import java.util.Date;

public class HtMerchantInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_merchant_info.ID
     *
     * @mbg.generated Fri Apr 28 09:47:45 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_merchant_info.SER_TYEP
     *
     * @mbg.generated Fri Apr 28 09:47:45 CST 2017
     */
    private Integer serTyep;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_merchant_info.M_NAME
     *
     * @mbg.generated Fri Apr 28 09:47:45 CST 2017
     */
    private String mName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_merchant_info.M_ADDRESS
     *
     * @mbg.generated Fri Apr 28 09:47:45 CST 2017
     */
    private String mAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_merchant_info.INFO
     *
     * @mbg.generated Fri Apr 28 09:47:45 CST 2017
     */
    private String info;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_merchant_info.M_DESC
     *
     * @mbg.generated Fri Apr 28 09:47:45 CST 2017
     */
    private String mDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_merchant_info.LOGO_URL
     *
     * @mbg.generated Fri Apr 28 09:47:45 CST 2017
     */
    private String logoUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_merchant_info.PWD
     *
     * @mbg.generated Fri Apr 28 09:47:45 CST 2017
     */
    private String pwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_merchant_info.MOBILE
     *
     * @mbg.generated Fri Apr 28 09:47:45 CST 2017
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_merchant_info.AREA
     *
     * @mbg.generated Fri Apr 28 09:47:45 CST 2017
     */
    private Integer area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_merchant_info.STATUS
     *
     * @mbg.generated Fri Apr 28 09:47:45 CST 2017
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_merchant_info.MARK_NUM
     *
     * @mbg.generated Fri Apr 28 09:47:45 CST 2017
     */
    private Long markNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_merchant_info.COORD
     *
     * @mbg.generated Fri Apr 28 09:47:45 CST 2017
     */
    private String coord;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_merchant_info.CREATE_ON
     *
     * @mbg.generated Fri Apr 28 09:47:45 CST 2017
     */
    private Date createOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_merchant_info.UPDATE_ON
     *
     * @mbg.generated Fri Apr 28 09:47:45 CST 2017
     */
    private Date updateOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_merchant_info.OPTIMIZED_LOCK
     *
     * @mbg.generated Fri Apr 28 09:47:45 CST 2017
     */
    private Integer optimizedLock;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_merchant_info.ID
     *
     * @return the value of ht_merchant_info.ID
     *
     * @mbg.generated Fri Apr 28 09:47:45 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_merchant_info.ID
     *
     * @param id the value for ht_merchant_info.ID
     *
     * @mbg.generated Fri Apr 28 09:47:45 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_merchant_info.SER_TYEP
     *
     * @return the value of ht_merchant_info.SER_TYEP
     *
     * @mbg.generated Fri Apr 28 09:47:45 CST 2017
     */
    public Integer getSerTyep() {
        return serTyep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_merchant_info.SER_TYEP
     *
     * @param serTyep the value for ht_merchant_info.SER_TYEP
     *
     * @mbg.generated Fri Apr 28 09:47:45 CST 2017
     */
    public void setSerTyep(Integer serTyep) {
        this.serTyep = serTyep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_merchant_info.M_NAME
     *
     * @return the value of ht_merchant_info.M_NAME
     *
     * @mbg.generated Fri Apr 28 09:47:45 CST 2017
     */
    public String getmName() {
        return mName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_merchant_info.M_NAME
     *
     * @param mName the value for ht_merchant_info.M_NAME
     *
     * @mbg.generated Fri Apr 28 09:47:45 CST 2017
     */
    public void setmName(String mName) {
        this.mName = mName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_merchant_info.M_ADDRESS
     *
     * @return the value of ht_merchant_info.M_ADDRESS
     *
     * @mbg.generated Fri Apr 28 09:47:45 CST 2017
     */
    public String getmAddress() {
        return mAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_merchant_info.M_ADDRESS
     *
     * @param mAddress the value for ht_merchant_info.M_ADDRESS
     *
     * @mbg.generated Fri Apr 28 09:47:45 CST 2017
     */
    public void setmAddress(String mAddress) {
        this.mAddress = mAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_merchant_info.INFO
     *
     * @return the value of ht_merchant_info.INFO
     *
     * @mbg.generated Fri Apr 28 09:47:45 CST 2017
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_merchant_info.INFO
     *
     * @param info the value for ht_merchant_info.INFO
     *
     * @mbg.generated Fri Apr 28 09:47:45 CST 2017
     */
    public void setInfo(String info) {
        this.info = info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_merchant_info.M_DESC
     *
     * @return the value of ht_merchant_info.M_DESC
     *
     * @mbg.generated Fri Apr 28 09:47:45 CST 2017
     */
    public String getmDesc() {
        return mDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_merchant_info.M_DESC
     *
     * @param mDesc the value for ht_merchant_info.M_DESC
     *
     * @mbg.generated Fri Apr 28 09:47:45 CST 2017
     */
    public void setmDesc(String mDesc) {
        this.mDesc = mDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_merchant_info.LOGO_URL
     *
     * @return the value of ht_merchant_info.LOGO_URL
     *
     * @mbg.generated Fri Apr 28 09:47:45 CST 2017
     */
    public String getLogoUrl() {
        return logoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_merchant_info.LOGO_URL
     *
     * @param logoUrl the value for ht_merchant_info.LOGO_URL
     *
     * @mbg.generated Fri Apr 28 09:47:45 CST 2017
     */
    public void setLogoUrl(String logoUrl) {
        this.logoUrl = logoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_merchant_info.PWD
     *
     * @return the value of ht_merchant_info.PWD
     *
     * @mbg.generated Fri Apr 28 09:47:45 CST 2017
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_merchant_info.PWD
     *
     * @param pwd the value for ht_merchant_info.PWD
     *
     * @mbg.generated Fri Apr 28 09:47:45 CST 2017
     */
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_merchant_info.MOBILE
     *
     * @return the value of ht_merchant_info.MOBILE
     *
     * @mbg.generated Fri Apr 28 09:47:45 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_merchant_info.MOBILE
     *
     * @param mobile the value for ht_merchant_info.MOBILE
     *
     * @mbg.generated Fri Apr 28 09:47:45 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_merchant_info.AREA
     *
     * @return the value of ht_merchant_info.AREA
     *
     * @mbg.generated Fri Apr 28 09:47:45 CST 2017
     */
    public Integer getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_merchant_info.AREA
     *
     * @param area the value for ht_merchant_info.AREA
     *
     * @mbg.generated Fri Apr 28 09:47:45 CST 2017
     */
    public void setArea(Integer area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_merchant_info.STATUS
     *
     * @return the value of ht_merchant_info.STATUS
     *
     * @mbg.generated Fri Apr 28 09:47:45 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_merchant_info.STATUS
     *
     * @param status the value for ht_merchant_info.STATUS
     *
     * @mbg.generated Fri Apr 28 09:47:45 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_merchant_info.MARK_NUM
     *
     * @return the value of ht_merchant_info.MARK_NUM
     *
     * @mbg.generated Fri Apr 28 09:47:45 CST 2017
     */
    public Long getMarkNum() {
        return markNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_merchant_info.MARK_NUM
     *
     * @param markNum the value for ht_merchant_info.MARK_NUM
     *
     * @mbg.generated Fri Apr 28 09:47:45 CST 2017
     */
    public void setMarkNum(Long markNum) {
        this.markNum = markNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_merchant_info.COORD
     *
     * @return the value of ht_merchant_info.COORD
     *
     * @mbg.generated Fri Apr 28 09:47:45 CST 2017
     */
    public String getCoord() {
        return coord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_merchant_info.COORD
     *
     * @param coord the value for ht_merchant_info.COORD
     *
     * @mbg.generated Fri Apr 28 09:47:45 CST 2017
     */
    public void setCoord(String coord) {
        this.coord = coord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_merchant_info.CREATE_ON
     *
     * @return the value of ht_merchant_info.CREATE_ON
     *
     * @mbg.generated Fri Apr 28 09:47:45 CST 2017
     */
    public Date getCreateOn() {
        return createOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_merchant_info.CREATE_ON
     *
     * @param createOn the value for ht_merchant_info.CREATE_ON
     *
     * @mbg.generated Fri Apr 28 09:47:45 CST 2017
     */
    public void setCreateOn(Date createOn) {
        this.createOn = createOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_merchant_info.UPDATE_ON
     *
     * @return the value of ht_merchant_info.UPDATE_ON
     *
     * @mbg.generated Fri Apr 28 09:47:45 CST 2017
     */
    public Date getUpdateOn() {
        return updateOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_merchant_info.UPDATE_ON
     *
     * @param updateOn the value for ht_merchant_info.UPDATE_ON
     *
     * @mbg.generated Fri Apr 28 09:47:45 CST 2017
     */
    public void setUpdateOn(Date updateOn) {
        this.updateOn = updateOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_merchant_info.OPTIMIZED_LOCK
     *
     * @return the value of ht_merchant_info.OPTIMIZED_LOCK
     *
     * @mbg.generated Fri Apr 28 09:47:45 CST 2017
     */
    public Integer getOptimizedLock() {
        return optimizedLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_merchant_info.OPTIMIZED_LOCK
     *
     * @param optimizedLock the value for ht_merchant_info.OPTIMIZED_LOCK
     *
     * @mbg.generated Fri Apr 28 09:47:45 CST 2017
     */
    public void setOptimizedLock(Integer optimizedLock) {
        this.optimizedLock = optimizedLock;
    }
}