package com.partner.hlife.pojo;

import java.util.Date;

public class HtMerchantExpand {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_merchant_expand.ID
     *
     * @mbg.generated Thu Apr 27 16:23:26 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_merchant_expand.MERCHANT_ID
     *
     * @mbg.generated Thu Apr 27 16:23:26 CST 2017
     */
    private Long merchantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_merchant_expand.URL
     *
     * @mbg.generated Thu Apr 27 16:23:26 CST 2017
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_merchant_expand.AREA
     *
     * @mbg.generated Thu Apr 27 16:23:26 CST 2017
     */
    private Integer area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_merchant_expand.ORDER_NUM
     *
     * @mbg.generated Thu Apr 27 16:23:26 CST 2017
     */
    private Integer orderNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_merchant_expand.CREATE_ON
     *
     * @mbg.generated Thu Apr 27 16:23:26 CST 2017
     */
    private Date createOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_merchant_expand.UPDATE_ON
     *
     * @mbg.generated Thu Apr 27 16:23:26 CST 2017
     */
    private Date updateOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_merchant_expand.OPTIMIZED_LOCK
     *
     * @mbg.generated Thu Apr 27 16:23:26 CST 2017
     */
    private Integer optimizedLock;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_merchant_expand.ID
     *
     * @return the value of ht_merchant_expand.ID
     *
     * @mbg.generated Thu Apr 27 16:23:26 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_merchant_expand.ID
     *
     * @param id the value for ht_merchant_expand.ID
     *
     * @mbg.generated Thu Apr 27 16:23:26 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_merchant_expand.MERCHANT_ID
     *
     * @return the value of ht_merchant_expand.MERCHANT_ID
     *
     * @mbg.generated Thu Apr 27 16:23:26 CST 2017
     */
    public Long getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_merchant_expand.MERCHANT_ID
     *
     * @param merchantId the value for ht_merchant_expand.MERCHANT_ID
     *
     * @mbg.generated Thu Apr 27 16:23:26 CST 2017
     */
    public void setMerchantId(Long merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_merchant_expand.URL
     *
     * @return the value of ht_merchant_expand.URL
     *
     * @mbg.generated Thu Apr 27 16:23:26 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_merchant_expand.URL
     *
     * @param url the value for ht_merchant_expand.URL
     *
     * @mbg.generated Thu Apr 27 16:23:26 CST 2017
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_merchant_expand.AREA
     *
     * @return the value of ht_merchant_expand.AREA
     *
     * @mbg.generated Thu Apr 27 16:23:26 CST 2017
     */
    public Integer getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_merchant_expand.AREA
     *
     * @param area the value for ht_merchant_expand.AREA
     *
     * @mbg.generated Thu Apr 27 16:23:26 CST 2017
     */
    public void setArea(Integer area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_merchant_expand.ORDER_NUM
     *
     * @return the value of ht_merchant_expand.ORDER_NUM
     *
     * @mbg.generated Thu Apr 27 16:23:26 CST 2017
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_merchant_expand.ORDER_NUM
     *
     * @param orderNum the value for ht_merchant_expand.ORDER_NUM
     *
     * @mbg.generated Thu Apr 27 16:23:26 CST 2017
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_merchant_expand.CREATE_ON
     *
     * @return the value of ht_merchant_expand.CREATE_ON
     *
     * @mbg.generated Thu Apr 27 16:23:26 CST 2017
     */
    public Date getCreateOn() {
        return createOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_merchant_expand.CREATE_ON
     *
     * @param createOn the value for ht_merchant_expand.CREATE_ON
     *
     * @mbg.generated Thu Apr 27 16:23:26 CST 2017
     */
    public void setCreateOn(Date createOn) {
        this.createOn = createOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_merchant_expand.UPDATE_ON
     *
     * @return the value of ht_merchant_expand.UPDATE_ON
     *
     * @mbg.generated Thu Apr 27 16:23:26 CST 2017
     */
    public Date getUpdateOn() {
        return updateOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_merchant_expand.UPDATE_ON
     *
     * @param updateOn the value for ht_merchant_expand.UPDATE_ON
     *
     * @mbg.generated Thu Apr 27 16:23:26 CST 2017
     */
    public void setUpdateOn(Date updateOn) {
        this.updateOn = updateOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_merchant_expand.OPTIMIZED_LOCK
     *
     * @return the value of ht_merchant_expand.OPTIMIZED_LOCK
     *
     * @mbg.generated Thu Apr 27 16:23:26 CST 2017
     */
    public Integer getOptimizedLock() {
        return optimizedLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_merchant_expand.OPTIMIZED_LOCK
     *
     * @param optimizedLock the value for ht_merchant_expand.OPTIMIZED_LOCK
     *
     * @mbg.generated Thu Apr 27 16:23:26 CST 2017
     */
    public void setOptimizedLock(Integer optimizedLock) {
        this.optimizedLock = optimizedLock;
    }
}