package com.partner.hlife.pojo;

public class TTestUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_test_user.id
     *
     * @mbg.generated Wed Apr 26 17:56:24 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_test_user.name
     *
     * @mbg.generated Wed Apr 26 17:56:24 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_test_user.age
     *
     * @mbg.generated Wed Apr 26 17:56:24 CST 2017
     */
    private Integer age;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_test_user.id
     *
     * @return the value of t_test_user.id
     *
     * @mbg.generated Wed Apr 26 17:56:24 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_test_user.id
     *
     * @param id the value for t_test_user.id
     *
     * @mbg.generated Wed Apr 26 17:56:24 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_test_user.name
     *
     * @return the value of t_test_user.name
     *
     * @mbg.generated Wed Apr 26 17:56:24 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_test_user.name
     *
     * @param name the value for t_test_user.name
     *
     * @mbg.generated Wed Apr 26 17:56:24 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_test_user.age
     *
     * @return the value of t_test_user.age
     *
     * @mbg.generated Wed Apr 26 17:56:24 CST 2017
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_test_user.age
     *
     * @param age the value for t_test_user.age
     *
     * @mbg.generated Wed Apr 26 17:56:24 CST 2017
     */
    public void setAge(Integer age) {
        this.age = age;
    }
}